# Generated by Django 5.2.6 on 2025-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='news',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Sepatu'), ('ball', 'Bola'), ('accessories', 'Aksesoris'), ('equipment', 'Peralatan Latihan'), ('bag', 'Tas Olahraga')], max_length=100),
        ),
    ]
