# Generated by Django 5.2.6 on 2025-09-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_rating_news_stock_alter_news_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Product',
        ),
    ]
